# Generated by Django 5.1 on 2024-08-26 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Excercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(default=None, upload_to="images")),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("correct", models.BooleanField(default=False)),
                (
                    "excercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teach.excercise",
                    ),
                ),
            ],
        ),
    ]
