# Generated by Django 5.1 on 2024-08-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teach", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="excercise",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="images"
            ),
        ),
    ]
