# Generated by Django 5.1 on 2024-08-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teach", "0002_alter_excercise_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="excercise",
            name="solution",
            field=models.TextField(default=""),
        ),
    ]
