# Generated by Django 5.1 on 2024-08-26 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0003_excercise_solution'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Excercise',
            new_name='Exercise',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='excercise',
            new_name='exercise',
        ),
    ]
