# Generated by Django 5.1 on 2024-08-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teach", "0007_alter_exercise_solution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="solution",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
