# Generated by Django 5.1 on 2024-09-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teach", "0009_solved_teaches"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solved",
            name="date",
        ),
    ]
